# Generated by Django 4.1.5 on 2023-01-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
        ("team", "0001_initial"),
    ]
