# Generated by Django 4.1.5 on 2023-01-09 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        help_text="팀을 구분하거나, 팀 뷰 url 생성을 위한 uuid 문자열",
                        max_length=23,
                        validators=[django.core.validators.MinLengthValidator(23)],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "admin_code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "security_question",
                    models.BigIntegerField(
                        choices=[
                            ("0", "고등학교 1학년 때의 수학 선생님의 성함은 무엇인가요?"),
                            ("1", "직접 입력"),
                        ],
                        default="0",
                    ),
                ),
                (
                    "custom_security_question",
                    models.CharField(max_length=200, null=True),
                ),
                ("security_answer", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "team",
            },
        ),
        migrations.CreateModel(
            name="TeamRegularEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_time",
                    models.CharField(default="00:00", help_text="HH:MM", max_length=5),
                ),
                (
                    "end_time",
                    models.CharField(default="24:00", help_text="HH:MM", max_length=5),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        max_length=23,
                        validators=[django.core.validators.MinLengthValidator(23)],
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ]
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_event",
                        to="team.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_regular_event",
            },
        ),
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
            ],
            options={
                "db_table": "subgroup",
            },
        ),
    ]
