# Generated by Django 4.1.5 on 2023-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="uuid",
            field=models.CharField(
                help_text="팀을 구분하거나, 팀 뷰 url 생성을 위한 uuid 문자열", max_length=23
            ),
        ),
    ]
