# Generated by Django 4.1.5 on 2023-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_alter_team_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="admin_code",
            field=models.CharField(max_length=6),
        ),
    ]
