# Generated by Django 4.1.5 on 2023-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_alter_team_admin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="security_question",
            field=models.BigIntegerField(
                choices=[(0, "고등학교 1학년 때의 수학 선생님의 성함은 무엇인가요?"), (1, "직접 입력")], default=0
            ),
        ),
    ]
