# Generated by Django 4.1.5 on 2023-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0004_alter_team_security_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamregularevent",
            name="day",
            field=models.IntegerField(
                choices=[
                    (0, "MON"),
                    (1, "TUE"),
                    (2, "WED"),
                    (3, "THU"),
                    (4, "FRI"),
                    (5, "SAT"),
                    (6, "SUN"),
                ]
            ),
        ),
    ]
