# Generated by Django 4.1.5 on 2023-01-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0006_alter_teamregularevent_uuid_teammember"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="teammember",
            table="team_member",
        ),
    ]
