# Generated by Django 4.1.5 on 2023-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0008_alter_teammember_subgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
