# Generated by Django 4.1.5 on 2023-01-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0009_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="end_time",
            field=models.CharField(default="24:00", help_text="HH:MM", max_length=5),
        ),
        migrations.AddField(
            model_name="team",
            name="start_time",
            field=models.CharField(default="00:00", help_text="HH:MM", max_length=5),
        ),
    ]
