# Generated by Django 4.1.5 on 2023-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamSecurityQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "question",
                    models.CharField(
                        choices=[
                            ("고등학교 1학년 때의 수학 선생님의 성함은 무엇인가요?", "High School Teacher"),
                            ("직접 입력", "Custom"),
                        ],
                        default="고등학교 1학년 때의 수학 선생님의 성함은 무엇인가요?",
                        max_length=200,
                    ),
                ),
                ("custom_question", models.CharField(max_length=200, null=True)),
                ("answer", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "team_security_question",
            },
        ),
    ]
