name: BisTime API Test Server

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: 유저이름
          MYSQL_PASSWORD: 유저 패스워드
          MYSQL_DATABASE: 데이터베이스 이름
          MYSQL_ROOT_PASSWORD: root 패스워드
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest